### ISSUE TITLE
Regarding issue in satasmodels

### ISSUE THREAD

**Issue by athiyan-s** [MasterMedo/daily-expense-manager#1]
![Screenshot_20221115_201759](https://user-images.githubusercontent.com/108874587/202191945-1d0b47c3-4354-40d6-8961-2378784918e9.png)

I'm a beginner in ML and I'm been using your daily-expense-manager repository for my project. i encountered an issue while running the code. I couldn't under the error that caused. 
the error is at line 171 (patsy Error)
I don't know how to solve it Could you please help me out

**Comment by MasterMedo** [comment]
Hi there :wave:

- Did you get this error with the data I provide in the project, or did you use your own data?

I'll assume you were using your own data, because I just downloaded the project and got it running on a newly bought Raspberry Pi. The only thing I had to change in the code was the [line 167](https://github.com/MasterMedo/daily-expense-manager/blob/master/manager.py#L167) to `import statsmodels.api as sm`.

From the error message you posted, I can see the error is happening [here](https://github.com/pydata/patsy/blob/master/patsy/highlevel.py#L174). This probably means your input data isn't formatted like my input data.
If I were in your shoes, I'd go through the code up to that point and check where the matrices are of different sizes when you use my data vs when you use your data. Or you could format your data to have the same columns and number of columns like the one I provide. Hope that helps!

**Comment by athiyan-s** [comment]
thank you Mislav Vuletić, This helped me a lot. I made the changes in my csv file and got them right. thank you so much.

**Comment by MasterMedo** [comment]
Happy to help. Good luck in your endavours.
